app/routes.py
import flask


DEFAULT_BLUEPRINT = flask.Blueprint("gallery", __name__)
"""The default blueprint for all app instances."""

ITEMS_PER_PAGE = 10
"""The number of items to show on a single page."""


def _abort(code: int) -> None:
    """Call flask.abort with the appropriate error message.

    Args:
        code (int): Status code.
    """

    match code:
        case 400:
            msg = "Bad Request."
        case 404:
            msg = "Resource Not Found."
        case _:
            msg = "An Unknown Error Occurred."

    flask.abort(code, msg)


@DEFAULT_BLUEPRINT.route("/")
def index() -> str:
    """Return the index page.

    Returns:
        str: The rendered HTML for the index page.
    """

    return path(path='')


@DEFAULT_BLUEPRINT.route("/<path:path>/")
def path(path: str) -> str:
    """Return the main directory page.

    Args:
        path (str): The path to the directory.

    Returns:
        str: The rendered HTML for the directory page.
    """

    # flask.current_app.logger.info(
    #     "Request for main page of %s.",
    #     path or "index")

    # flask.current_app.logger.info(
    #     "Returning main page of %s.",
    #     path or "index")

    data = flask.current_app.config["GALLERY_DATA"]["directories"].get(path)
    if data:
        return flask.render_template(
            "index.html", breadcrumbs=data["breadcrumbs"], path=path, items=[], last=data["count"] <= 0)
    elif path == '':
        return flask.render_template(
            "index.html", breadcrumbs=[], path=path, items=[], last=data["count"] <= 0)

    # flask.current_app.logger.info("Path not found: '%s'.", path or "index")
    _abort(404)


@DEFAULT_BLUEPRINT.route("/pages")
def pages():
    """Return a gallery page.

    Returns:
        str: The rendered HTML for the gallery page.
    """

    path = flask.request.args.get("path", '')
    page = flask.request.args.get("page", '1')
    recurse = flask.request.args.get("recurse", '')

    # flask.current_app.logger.info(
    #     "Request for page %s of %s.",
    #     page,
    #     path or "index")

    try:
        page = int(page)
    except ValueError:
        # flask.current_app.logger.info("Invalid page number: '%s'.", page)
        _abort(400)

    data = flask.current_app.config["GALLERY_DATA"]["directories"][path]

    if not data:
        # flask.current_app.logger.info("Path not found: '%s'.", path or
        # "index")
        _abort(404)

    start = (page - 1) * ITEMS_PER_PAGE
    end = start + ITEMS_PER_PAGE

    if recurse:
        items = []

        def _recurse(item_list):
            for item in item_list:
                if item.type == "directory":
                    _recurse(
                        flask.current_app.config["GALLERY_DATA"]["directories"][item.path]["items"])
                else:
                    items.append(item)

        _recurse(data["items"])

        last = len(items) <= end
        items = items[start:end]

        # flask.current_app.logger.info(
        #     "Returning page %d of %s.", page, path or "index")
        return flask.render_template(
            "index.html", path=path, items=items, last=last)
    else:
        items = data["items"][start:end]
        last = data["count"] <= end

        if items:
            # flask.current_app.logger.info(
            #     "Returning page %d of %s.", page, path or "index")
            return flask.render_template(
                "index.html", path=path, items=items, last=last)

    # flask.current_app.logger.info(
    #     "Page %d not found for %s.", page, path or "index")
    _abort(404)


@DEFAULT_BLUEPRINT.route("/media/<path:path>")
def media(path: str) -> flask.Response:
    """Return a media file.

    Args:
        path (str): The path to the media file.

    Returns:
        str : The media file.
    """

    # flask.current_app.logger.info(
    #     "Request for media file: '%s'.", path)

    data_path = path.rstrip('/')
    if data_path in flask.current_app.config["GALLERY_DATA"]["media_files"]:
        if path and path.endswith('/'):
            path = path.rstrip('/')

            # flask.current_app.logger.info(
            #     "Redirecting to: '%s'.", path)
            return flask.current_app.redirect(
                flask.current_app.url_for("page", path=path))

        # flask.current_app.logger.info("Returning media file: '%s'.", path)
        return flask.send_from_directory(
            flask.current_app.config["MEDIA_DIR"], path)

    # flask.current_app.logger.info("Media file not found: '%s'.", path)
    _abort(404)


@DEFAULT_BLUEPRINT.route("/thumbnails/<path:path>")
def thumbnails(path: str) -> flask.Response:
    """Return a thumbnail file.

    Args:
        path (str): The path to the thumbnail file.

    Returns:
        str : The thumbnail file.
    """

    # flask.current_app.logger.info(
    #     "Request for thumbnail file: '%s'.", path)

    data_path = path.rstrip('/')
    if data_path in flask.current_app.config["GALLERY_DATA"]["thumbnails"]:
        if path and path.endswith('/'):
            path = path.rstrip('/')

            # flask.current_app.logger.info(
            #     "Redirecting to: '%s'.", path)
            return flask.current_app.redirect(
                flask.current_app.url_for("page", path=path))

        # flask.current_app.logger.info("Returning thumbnail file: '%s'.", path)
        return flask.send_from_directory(
            flask.current_app.config["THUMBNAILS_DIR"], path)

    # flask.current_app.logger.info("Thumbnail not found: '%s'.", path)
    _abort(404)

app/templates/gallery.html
{% for item in items %}
    {% if item.type == "image" %}
    <a
        class="gallery-item media-item d-flex flex-column overflow-hidden"
        data-fancybox="gallery"
        data-src="{{ url_for('gallery.media', path=item.path) }}"
        data-download-src="{{ url_for('gallery.media', path=item.path) }}"
    >
        <img
            class="d-block"
            src="{{ url_for('gallery.thumbnails', path=item.thumb) }}"
            alt="{{ item.name }}"
            loading="lazy"
        />
        <div class="media-info text-light user-select-all">
            <div class="media-title">{{ item.name }}</div>
        </div>
    </a>
    {% elif item.type == "video" %}
    <a
        class="gallery-item media-item d-flex flex-column overflow-hidden"
        data-fancybox="gallery"
        data-src="{{ url_for('gallery.media', path=item.path) }}"
        data-download-src="{{ url_for('gallery.media', path=item.path) }}"
        data-width="100%"
        data-height="100%"
    >
        <img
            class="d-block"
            src="{{ url_for('gallery.thumbnails', path=item.thumb) }}"
            alt="{{ item.name }}"
            loading="lazy"
        />
        <div
            class="video-overlay d-flex position-absolute justify-content-center align-items-center overflow-hidden rounded-circle top-50 start-50 translate-middle bg-transparent border border-primary shadow"
        >
            <svg
                class="bi bi-play-circle-fill opacity-75 text-black bg-primary"
                xmlns="http://www.w3.org/2000/svg"
                width="50"
                height="50"
                fill="currentColor"
                viewBox="0 0 16 16"
            >
                <path
                    d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zM6.79 5.093A.5.5 0 0 0 6 5.5v5a.5.5 0 0 0 .79.407l3.5-2.5a.5.5 0 0 0 0-.814l-3.5-2.5z"
                />
            </svg>
        </div>
        <div class="media-info text-light user-select-all">
            <div class="media-title">{{ item.name }}</div>
        </div>
    </a>
    {% else %}
    <a
        class="gallery-item folder-item d-flex flex-column overflow-hidden"
        href="{{ url_for('gallery.path', path=item.path) }}"
    >
        <img
            class="d-block"
            src="{{ url_for('gallery.thumbnails', path=item.thumbnail.thumb) }}"
            alt="{{ item.name }}"
            loading="lazy"
        />
        <div class="media-info text-light user-select-all">
            <div class="media-title">{{ item.name }}</div>
        </div>
        <div class="folder-badge text-light user-select-all">
            <i class="fas fa-folder-open"></i>
            <span>{{ item.count if item.count else "empty" }}</span>
        </div>
    </a>
    {% endif %}
{% endfor %}

app/templates/index.html
<!DOCTYPE html>
<html lang="en" data-bs-theme="dark">
    <head>
        <meta charset="utf-8" />
        <meta
            name="viewport"
            content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no"
        />
        <meta name="description" content="Media Gallery Web App" />
        <meta name="author" content="Jore github.com/jorexdeveloper" />

        <title>Gallery</title>

        <link
            rel="icon"
            type="image/png"
            sizes="512x512"
            href="{{ url_for('static', filename='assets/icons/android-chrome-512x512.png') }}"
        />

        <!-- Fonts -->
        <!-- <link
            rel="stylesheet"
            href="{{ url_for('static', filename='assets/fonts/orbitron/v34/css/style.css') }}"
        /> -->

        <!-- CSS Libraries -->
        <link
            rel="stylesheet"
            href="{{ url_for('static', filename='assets/lib/font-awesome/v6.4.0/css/all.min.css') }}"
        />
        <link
            rel="stylesheet"
            href="{{ url_for('static', filename='assets/lib/bootstrap/v5.3.7/css/bootstrap.min.css') }}"
        />
        <link
            rel="stylesheet"
            href="{{ url_for('static', filename='assets/lib/bootstrap-icons/v1.13.1/bootstrap-icons.min.css') }}"
        />
        <link
            rel="stylesheet"
            href="{{ url_for('static', filename='assets/lib/ui/v6.0.34/dist/fancybox/fancybox.css') }}"
        />
        <!-- <link
            rel="stylesheet"
            href="{{ url_for('static', filename='assets/lib/animate/v3.5.2/animate.min.css') }}"
        /> -->
        <link
            rel="stylesheet"
            href="{{ url_for('static', filename='assets/lib/video-js/v8.21.1/video-js.css') }}"
        />

        <!-- Custom CSS -->
        <link
            rel="stylesheet"
            href="{{ url_for('static', filename='css/main.css') }}"
        />
        <link
            rel="stylesheet"
            href="{{ url_for('static', filename='css/gallery.css') }}"
        />
    </head>

    <body class="d-flex flex-column min-vw-100 min-vh-100 p-0 m-0">
        <main
            class="container-fluid flex-fill d-flex flex-column w-100 h-100 p-0 m-0"
        >
            <div class="gallery-layout container-xl m-0">
                <div
                    class="gallery-container container-xl"
                    data-url="{{ url_for('gallery.pages') }}"
                    data-last="{{ 'true' if last else 'false' }}"
                    data-path="{{ path }}"
                >
                    <div class="gallery-item-sizer"></div>
                    <div class="gallery-gutter-sizer"></div>
                    {% include "gallery.html" %}
                </div>
                <div
                    class="page-load-status container-xl d-flex flex-column align-items-center justify-content-center"
                >
                    <div
                        class="infinite-scroll-request loader-ellips position-relative p-3 m-3"
                    >
                        <span
                            class="loader-ellips__dot d-block position-absolute rounded-circle bg-primary"
                        ></span>
                        <span
                            class="loader-ellips__dot d-block position-absolute rounded-circle bg-primary"
                        ></span>
                        <span
                            class="loader-ellips__dot d-block position-absolute rounded-circle bg-primary"
                        ></span>
                        <span
                            class="loader-ellips__dot d-block position-absolute rounded-circle bg-primary"
                        ></span>
                    </div>
                    <div
                        class="infinite-scroll-error d-flex flex-column align-items-center justify-content-center p-3 m-3 d-none"
                    >
                        <p class="text-center text-wrap fs-6 user-select-none">
                            Failed to load! Check your internet connection and
                            try again.
                        </p>
                        <button
                            id="retry-button"
                            type="button"
                            class="btn btn-primary"
                        >
                            Retry
                        </button>
                    </div>
                </div>
                {% if not last %}
                <div id="next-page-selector"></div>
                {% endif %}
            </div>
        </main>

        <footer class="container-fluid p-0">
            <div
                class="container-xl d-flex flex-column flex-lg-row align-items-center justify-content-center border-top p-3 wow fadeIn"
            >
                <span class="text-center p-1 user-select-none">
                    License · Terms · Privacy Policy
                </span>
                <span class="text-center p-1 user-select-none">
                    Copyright &copy; 2025
                    <a href="https://jorexdeveloper.github.io/jorexdeveloper/"
                        >Jore</a
                    >
                </span>
            </div>
        </footer>

        <!-- JS Libraries -->
        <script src="{{ url_for('static', filename='assets/lib/jquery/v3.7.1/jquery.min.js.js') }}"></script>
        <script src="{{ url_for('static', filename='assets/lib/bootstrap/v5.3.7/js/bootstrap.bundle.min.js') }}"></script>
        <script src="{{ url_for('static', filename='assets/lib/packery/v2.1.2/packery.pkgd.min.js.js') }}"></script>
        <script src="{{ url_for('static', filename='assets/lib/infinite-scroll/v5.0.0/infinite-scroll.pkgd.min.js.js') }}"></script>
        <!-- <script src="{{ url_for('static', filename='assets/lib/draggabilly/v3.0.0/draggabilly.pkgd.min.js') }}"></script> -->
        <script src="{{ url_for('static', filename='assets/lib/ui/v6.0.34/dist/fancybox/fancybox.umd.js') }}"></script>
        <script src="{{ url_for('static', filename='assets/lib/video-js/v8.21.1/video.min.js') }}"></script>
        <!-- <script src="{{ url_for('static', filename='assets/lib/wow/v1.3.0/wow.min.js') }}"></script> -->
        <script src="{{ url_for('static', filename='js/main.js') }}"></script>
    </body>
</html>